### ISSUE TITLE
Dwm-msg Examples in wiki?

### ISSUE THREAD

**Issue by rensenware** [mihirlad55/dwm-ipc#10]
The wiki doesn't contain any useful examples of how to use dwm-msg run commands, just a description of how it works that isn't helpful to a now user.

**Comment by mihirlad55** [comment]
Good point, I'll add a few examples

**Comment by mihirlad55** [comment]
Ended up being more than a few. What do you think?

https://github.com/mihirlad55/dwm-ipc/wiki/dwm-msg
https://github.com/mihirlad55/dwm-ipc/wiki/dwm-msg-Run-Command
https://github.com/mihirlad55/dwm-ipc/wiki/dwm-msg-Subscribe

**Comment by rensenware** [comment]
These are really helpful, the only thing I'd add would be a spawn example. Thanks!

**Comment by mihirlad55** [comment]
I decided not to put a `spawn` example because its not very useful with `dwm-msg`. It literally just starts a program whose execution command is defined in `config.h`, but I'll add it anyway.

**Comment by mihirlad55** [comment]
Actually, lol, I just realized it's currently impossible to use the `spawn` command since there is currently no way to get the address of a char array that defines a possible command to use. I'll probably remove this command in the next release since it's basically useless. Is there anything else?

**Comment by rensenware** [comment]
Thank you! This really helps with scripts.

**Comment by rensenware** [comment]
No, I think you covered everything else. I was using the spawn command, or the equivalent of it anyways, on another window manager to be able to send notifications from a systemd service without having to mess with xorg security, which probably wasn't a great idea anyways. Thanks!

**Comment by mihirlad55** [comment]
No problem
