### ISSUE TITLE
dwm-msg segmentation fault when running with no arguments 

### ISSUE THREAD

**Issue by bakkeby** [mihirlad55/dwm-ipc#16]
https://github.com/mihirlad55/dwm-ipc/blob/981329b99571fd0e967065d31e9c0e35d870743d/dwm-msg.c#L502

I'd recommend adding `i < argc &&` to that if statement to avoid referring to an array index that does not exist when running dwm-msg with no arguments.
```c
if (i < argc && strcmp(argv[i], "--ignore-reply") == 0) {
```
I can raise a pull request if you want.

**Comment by mihirlad55** [comment]
Thanks for reporting this issue. It's been fixed in v1.5.7.
