### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by ghost** [mihirlad55/dwm-ipc#18]
<pre><font color="#42E66C"><u style="text-decoration-style:single">sudo</u></font> <font color="#42E66C">make</font> clean install
[sudo] password for ritikesh: 
rm -f dwm dwm-msg drw.o dwm.o util.o dwm-6.2.tar.gz
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -I/usr/include/yajl -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=&quot;6.2&quot; -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lyajl
CC       = cc
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -I/usr/include/yajl -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\&quot;6.2\&quot; -DXINERAMA drw.c
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -I/usr/include/yajl -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\&quot;6.2\&quot; -DXINERAMA dwm.c
cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -I/usr/include/yajl -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION=\&quot;6.2\&quot; -DXINERAMA util.c
cc -o dwm drw.o dwm.o util.o -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lyajl
/usr/bin/ld: dwm.o: undefined reference to symbol &apos;XRenderFindVisualFormat&apos;
/usr/bin/ld: /usr/lib/libXrender.so.1: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:26: dwm] Error 1</pre>

**Comment by ghost** [comment]
i have patched dwm several times this is the first time i got something like this

**Comment by bakkeby** [comment]
For what it is worth the above error was in relation to using the alpha patch and not having `-lXrender` in config.mk. The user that opened this issue has been deleted so this can be closed.

**Comment by mihirlad55** [comment]
Thanks for the info!
