### ISSUE TITLE
Is it possaible to use sxhkd?

### ISSUE THREAD

**Issue by simanga-dev** [mihirlad55/dwm-ipc#19]
This patch looks like something I am looking for, I want to run all my key mapping through an external program like sxhkd. is that possible using this vision of dwm?

**Comment by bakkeby** [comment]
Hi @hendry-khoza, yes you can run pretty much every key binding through sxhkd with this patch, but button clicks you'll likely want to keep within dwm.

**Comment by simanga-dev** [comment]
Thank you
