### ISSUE TITLE
Cannot Compile, functions ipcsockpath, ipccommansd undeclared

### ISSUE THREAD

**Issue by rensenware** [mihirlad55/dwm-ipc#9]
Arch Linux, dwm 6.2. Patches applied: dwm-autostart-20200610-cb3f58a.diff, dwm-anybar-20200721-bb2e722.diff, dwm-ipc-20200729-f07cac6.diff, in that order. Patches merged normally with patch -p1 < patches/foo.bar. When compiling with sudo make install, the following is spat into the console:
`dwm build options:`

`CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -I/usr/include/yajl -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION="6.2" -DXINERAMA`

`LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lyajl`

`CC       = cc`

`cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -I/usr/include/yajl -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA drw.c`

`cc -c -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -I/usr/include/yajl -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=200809L -DVERSION=\"6.2\" -DXINERAMA dwm.c`

`dwm.c: In function ‘setupepoll’:`

`dwm.c:1840:15: error: ‘ipcsockpath’ undeclared (first use in this function)`

` 1840 |  if (ipc_init(ipcsockpath, epoll_fd, ipccommands, LENGTH(ipccommands)) < 0) {`

`      |               ^~~~~~~~~~~`

`dwm.c:1840:15: note: each undeclared identifier is reported only once for each function it appears in`

`dwm.c:1840:38: error: ‘ipccommands’ undeclared (first use in this function); did you mean ‘ipc_commands’?`

` 1840 |  if (ipc_init(ipcsockpath, epoll_fd, ipccommands, LENGTH(ipccommands)) < 0) {`

`      |                                      ^~~~~~~~~~~`

`      |                                      ipc_commands`

`At top level:`

`dwm.c:1719:1: warning: ‘setlayoutsafe’ defined but not used [-Wunused-function]`

` 1719 | setlayoutsafe(const Arg *arg)`

`      | ^~~~~~~~~~~~~`

`make: *** [Makefile:18: dwm.o] Error 1`

**Comment by mihirlad55** [comment]
Check your `config.h`, it wasn't updated with the new additions from the patches in your `config.def.h`

**Comment by rensenware** [comment]
That was it. Thank you.
